<?php

return [

    'data_path' => env('BIBLE_DATA_PATH', base_path('biblia_catolica_73_es_exp_compacto.json')),

    /*
    | Abreviaturas alinhadas às chaves do JSON (73 livros — Bíblia Católica).
    */
    'books' => [
        'Gn' => 'Génesis',
        'Ex' => 'Éxodo',
        'Lv' => 'Levítico',
        'Nm' => 'Números',
        'Dt' => 'Deuteronomio',
        'Jos' => 'Josué',
        'Jue' => 'Jueces',
        'Rut' => 'Rut',
        '1Sam' => '1 Samuel',
        '2Sam' => '2 Samuel',
        '1Re' => '1 Reyes',
        '2Re' => '2 Reyes',
        '1Cro' => '1 Crónicas',
        '2Cro' => '2 Crónicas',
        'Esd' => 'Esdras',
        'Neh' => 'Nehemías',
        'Tob' => 'Tobías',
        'Jdt' => 'Judit',
        'Est' => 'Ester',
        '1Mac' => '1 Macabeos',
        '2Mac' => '2 Macabeos',
        'Job' => 'Job',
        'Sal' => 'Salmos',
        'Prov' => 'Proverbios',
        'Ecl' => 'Eclesiastés',
        'Cant' => 'Cantar de los Cantares',
        'Sab' => 'Sabiduría',
        'Eclo' => 'Eclesiástico',
        'Is' => 'Isaías',
        'Jer' => 'Jeremías',
        'Lam' => 'Lamentaciones',
        'Bar' => 'Baruc',
        'Ez' => 'Ezequiel',
        'Dan' => 'Daniel',
        'Os' => 'Oseas',
        'Jl' => 'Joel',
        'Am' => 'Amós',
        'Abd' => 'Abdías',
        'Jon' => 'Jonás',
        'Miq' => 'Miqueas',
        'Nah' => 'Nahum',
        'Hab' => 'Habacuc',
        'Sof' => 'Sofonías',
        'Hag' => 'Ageo',
        'Zac' => 'Zacarías',
        'Mal' => 'Malaquías',
        'Mt' => 'Mateo',
        'Mc' => 'Marcos',
        'Lc' => 'Lucas',
        'Jn' => 'Juan',
        'Hch' => 'Hechos',
        'Rom' => 'Romanos',
        '1Cor' => '1 Corintios',
        '2Cor' => '2 Corintios',
        'Gal' => 'Gálatas',
        'Ef' => 'Efesios',
        'Flp' => 'Filipenses',
        'Col' => 'Colosenses',
        '1Tes' => '1 Tesalonicenses',
        '2Tes' => '2 Tesalonicenses',
        '1Tim' => '1 Timoteo',
        '2Tim' => '2 Timoteo',
        'Tit' => 'Tito',
        'Flm' => 'Filemón',
        'Heb' => 'Hebreos',
        'Stg' => 'Santiago',
        '1Pe' => '1 Pedro',
        '2Pe' => '2 Pedro',
        '1Jn' => '1 Juan',
        '2Jn' => '2 Juan',
        '3Jn' => '3 Juan',
        'Jud' => 'Judas',
        'Ap' => 'Apocalipsis',
    ],

];
